# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: pwk_dev
  pool: 5
  username: madmax
  password: madmaxdx


production:
  database: pwk_production
  adapter: postgresql
  host: localhost
  password: